### ISSUE TITLE
plz I need help

### ISSUE THREAD

**Issue by raedaf** [halogeeni/multithread-knapsack#1]
where i can find the code of 
package aleksirasio.advancedalgorithms.lab06.multithread;

import aleksirasio.advancedalgorithms.lab06.bruteforce.Item;
import aleksirasio.advancedalgorithms.lab06.bruteforce.Solution;

i think these missing how i can update code?

**Comment by halogeeni** [comment]
Just pushed a commit w/ missing Item & Solution classes. Thanks for the heads up.
The package just denotes my personal project hierarchy. Your IDE should be able to help you with that.
Have fun!
